apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: xraylab-1
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          env:
            - name: database-user
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-user
            - name: database-password
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-password
            - name: database-host
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-host
            - name: database-db
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-db
            - name: service_point
              valueFrom:
                configMapKeyRef:
                  name: service-point
                  key: url-external
            - name: bucket-base-name
              valueFrom:
                configMapKeyRef:
                  name: buckets-config
                  key: bucket-base-name
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 1G
            requests:
              cpu: 400m
              memory: 100M
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler