global:
  pattern: medical-diagnosis

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  xraylab:
    s3:
      # Values for S3 bucket access
      # bucketSource: "provide s3 bucket name where images are stored"
      bucketSource: validated-patterns-md-xray
      # Bucket base name used for image-generator and image-server applications.
      bucketBaseName: "xray-source"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
