apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: xraylab-grafana
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    dashboards: "grafana"
spec:
  deployment:
    skipCreateAdminAccount: true
    envFrom:
      - secretRef:
          name: grafana-creds
  route: {}
  config:
    auth:
      disable_signout_menu: "true"
    auth.anonymous:
      enabled: "true"
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
