apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: xraylab-grafana
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      deployment:
        template:
          spec:
            containers:
              - name: grafana
                env:
                  - name: GF_SECURITY_ADMIN_USER
                    valueFrom:
                      secretKeyRef:
                        key: GF_SECURITY_ADMIN_USER
                        name: grafana-creds
                  - name: GF_SECURITY_ADMIN_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: GF_SECURITY_ADMIN_PASSWORD
                        name: grafana-creds 
  route: {}
  config:
    auth:
      disable_signout_menu: "true"
      anonymous:
        enabled: "true"
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
