apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: job-wait-for-database
  namespace: xraylab-1
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=Available=true deployment/xraylabdb -n xraylab-1 --timeout=900s
        name: wait-for-xraylab-database
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: xraylab-1-sa
      serviceAccountName: xraylab-1-sa
      terminationGracePeriodSeconds: 60
