apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.kafka.app }}
  name: {{ .Values.kafka.app }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.app }}
    spec:
      containers:
        - name: {{ .Values.kafka.app }}
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: {{ .Values.kafka.service.port }}
          env:
          {{- range .Values.kafka.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
