apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
  name: create-s3-secret
  namespace: xraylab-1
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=complete job/job-odf-storagecluster-complete --timeout=600s
          '/tmp/create-s3-secret.sh'
        name: create-s3-secret
        volumeMounts:
          - mountPath: /tmp/create-s3-secret.sh
            name: create-s3-secret
            subPath: create-s3-secret.sh
      volumes:
        - name: create-s3-secret
          configMap:
            name: create-s3-secret
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: xraylab-1-sa
      serviceAccountName: xraylab-1-sa
      terminationGracePeriodSeconds: 400
