apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
  name: job-odf-cephobjectstore-complete
  namespace: xraylab-1
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
           '/tmp/wait-for-objectstore.sh'
        name: wait-odf-cephobjectstore-complete
        volumeMounts:
          - mountPath: /tmp/wait-for-objectstore.sh
            name: wait-for-objectstore
            subPath: wait-for-objectstore.sh
      volumes:
        - name: wait-for-objectstore
          configMap:
            name: wait-for-objectstore
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: xraylab-1-sa
      serviceAccountName: xraylab-1-sa
      terminationGracePeriodSeconds: 60
