---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.database.name }}
  namespace: xraylab-1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=True
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}
  storageClassName: {{ .Values.global.storageClassName }}
  volumeMode: {{ .Values.pvc.volumeMode }}